name: Zig Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  zig-build-test:
    strategy:
      matrix:
        settings:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-24.04-arm
            arch: aarch64
          # - os: macos-13 hashtree doesn't support MacOS Intel
          #   arch: x86_64
          - os: macos-latest
            arch: aarch64

    runs-on: ${{ matrix.settings.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive # Ensures submodules are cloned
          fetch-depth: 0        # Fetches the entire history for all branches

      - name: Print OS ${{ matrix.settings.os }}
        run: uname -a
      - name: Print Architecture ${{ matrix.settings.arch }}
        run: uname -m

      - name: Install Zig
        uses: mlugg/setup-zig@v1
        with:
          version: "0.14.0" # Set the required Zig version

      - name: Build and Test
        run: |
          zig build test